CREATE TABLE CELULAR(
ID_NUMBER number PRIMARY KEY,
MODELO NVARCHAR2(100),
MARCA NVARCHAR2(100),
PRECIO NUMBER,
RAM NUMBER,
PAIS NVARCHAR2(100)
);


INSERT INTO CELULAR VALUES(1,'OPPO A7','XIAOMI',7000,6,'CHINA');
INSERT INTO CELULAR VALUES(2,'APPO X3 PRO','XIAOMI',8000,6,'CHINA');
INSERT INTO CELULAR VALUES(3,'OPPO RENO 5 LITE','XIAOMI',8500,8,'CHINA');
INSERT INTO CELULAR VALUES(4,'SAMSUNG S20','SAMSUNG',9000,8,'KOREA');
INSERT INTO CELULAR VALUES(5,'ONE HYPPER','MOTOROLA',4500,4,'USA');
INSERT INTO CELULAR VALUES(6,'GALAXY S20 ULTRA','SAMSUNG',25000,8,'KOREA');
INSERT INTO CELULAR VALUES(7,'A7','SAMSUNG',5500,4,'KOREA');
INSERT INTO CELULAR VALUES(8,'OPPO A53','XIAOMI',4600,4,'CHINA');
INSERT INTO CELULAR VALUES(9,'IPHONE X','IPHONE',7500,4,'USA');
INSERT INTO CELULAR VALUES(10,'IPHONE 13 PRO MAX','IPHONE',43000,4,'USA');
INSERT INTO CELULAR VALUES(11,'G9 PLUS',NULL,6000,4,'USA');



SELECT * FROM CELULAR;

SELECT COUNT(ID_NUMBER) AS CONTADOR FROM CELULAR WHERE MARCA = 'XIAOMI';

SELECT SUM(PRECIO) SUMA FROM CELULAR WHERE MARCA = 'SAMSUNG';

SELECT  MAX(PRECIO) PRECIO_MAXIMO FROM CELULAR;

SELECT ID_NUMBER, LOWER(MODELO) MODELO,MARCA, PRECIO, RAM, PAIS FROM CELULAR;

SELECT ID_NUMBER, MODELO, MARCA, CONCAT('$ ', PRECIO) PRECIO, RAM, PAIS FROM CELULAR;

SELECT COUNT(ID_NUMBER) CONTADOR, MARCA FROM CELULAR GROUP BY MARCA;



CREATE TABLE PELICULAS(
ID_PELICULA NUMBER PRIMARY KEY,
NOMBRE VARCHAR2(80),
GENERO VARCHAR2(80),
PRECIO NUMBER,
DURACION NUMBER
);

INSERT INTO PELICULAS VALUES(1, 'GLADIADOR', 'ACCION', 1234, 180);
INSERT INTO PELICULAS VALUES(2, 'LA MALDICION', 'TERROR', 3456, 120);
INSERT INTO PELICULAS VALUES(3, 'EL ARO', 'TERROR', 1450, 150);
INSERT INTO PELICULAS VALUES(4, 'RAMBO', 'ACCION', 1346, 80);
INSERT INTO PELICULAS VALUES(5, 'EL CONJURO', 'TERROR', 1234, 180);
INSERT INTO PELICULAS VALUES(6, 'EL CASTILLO VAGABUNDO', 'ANI,ACION', 1434, 120);
INSERT INTO PELICULAS VALUES(7, 'LA CIUDAD DE DIOS', 'ACCION', 1356, 90);
INSERT INTO PELICULAS VALUES(8, 'EL BUENO, EL MALO Y EL FEO', 'ACCION', 3462, 120);
INSERT INTO PELICULAS VALUES(9, 'JOHN ENGLISH', 'COMEDIA', 3452, 190);
INSERT INTO PELICULAS VALUES(10, 'BLADE RUNNER', 'CIENCIA FICCION', 1234, 180);

SELECT * FROM PELICULAS ORDER BY NOMBRE;

SELECT COUNT(ID_PELICULA) CONTADOR, GENERO FROM PELICULAS GROUP BY GENERO;

SELECT  MAX(DURACION) DURACION_MAXIMO FROM PELICULAS;

SELECT  MIN(DURACION) DURACION_MIN FROM PELICULAS;

SELECT * FROM PELICULAS WHERE PRECIO BETWEEN 2000 AND 5000;

select id_PELICULA, NOMBRE, GENERO, PRECIO, DURACION
FROM PELICULAS
WHERE PRECIO = (SELECT MAX(PRECIO) PRECIO_MAXIMO FROM PELICULAS);


CREATE TABLE PERSONA2(
ID NUMBER PRIMARY KEY,
NOMBRE VARCHAR2(100),
APP VARCHAR2(100),
APM VARCHAR2(100),
GENERO NUMBER,
EDAD NUMBER,
ESTADOCIVIL NUMBER
);


INSERT INTO PERSONA2 VALUES (1, 'LUIS', 'LOBATO', 'CAZARES', 1, 27, 4);
INSERT INTO PERSONA2 VALUES (2, 'AXEL', 'GARCIA', 'PEREZ', 1, 23, 1);
INSERT INTO PERSONA2 VALUES (3, 'MARIANA', 'GOMEZ', 'ISLAS', 2, 27, 1);

SELECT * FROM PERSONA2;

SELECT ID, NOMBRE, APP, APM, 
GENERO,(
CASE GENERO 
WHEN 1 THEN 'MASCULINO'
WHEN 2 THEN 'FEMENINO'
ELSE 'SIN GENERO' END
) AS DETALLE_GENERO,EDAD, 
ESTADOCIVIL,(
CASE ESTADOCIVIL
WHEN 1 THEN 'SOLTERO'
WHEN 2 THEN 'CASADO'
WHEN 3 THEN 'DIVORCIADO'
WHEN 4 THEN 'UNION LIBRE'
WHEN 5 THEN 'VIUDO'
ELSE 'SIN DEFINIR' END) AS DETALLE_ESTADOCIVIL
FROM PERSONA2;


CREATE TABLE CANCION(
ID NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(100),
GENERO NUMBER,
DURACION NUMBER,
CANTANTE NVARCHAR2(100),
IDIOMA NUMBER
);

INSERT INTO CANCION VALUES ('HAPPY', 1, 120, 'MITSKI', 1);
INSERT INTO CANCION VALUES ('TRISTE CACNION DE AMOR', 2, 90, 'ELTRI', 2);
INSERT INTO CANCION VALUES ('ARREGLAME EL ALMA', 7, 130, 'PANTEONROCOCO', 2);
INSERT INTO CANCION VALUES ('MUJER CONTRA MUJER', 1, 600, 'MECANO', 2);
INSERT INTO CANCION VALUES ('QUIERO VER', 2, 120, 'CAFETACUVA', 2);
INSERT INTO CANCION VALUES ('DUTCHLAND', 2, 150, 'RAMMSTEIN', 4);
INSERT INTO CANCION VALUES ('PEDRO NAVAJA', 5, 80, 'RUBEN BLADES', 2);
INSERT INTO CANCION VALUES ('CHUNTARO STYLE', 8, 130, 'LA MALDITA VECINDAD', 2);
INSERT INTO CANCION VALUES ('KANDY PERREO', 3, 190, 'NOSE', 2);
INSERT INTO CANCION VALUES ('MON AMOUR MON AMIE', 1, 97, 'LAFORETTE', 3);

SELECT * FROM CANCION;

SELECT ID, NOMBRE,
GENERO,(
CASE GENERO 
WHEN 1 THEN 'POP'
WHEN 2 THEN 'ROCK'
WHEN 3 THEN 'REGUETTON'
WHEN 4 THEN 'BALADA'
WHEN 5 THEN 'CUMBIA'
WHEN 6 THEN 'SALSA'
WHEN 7 THEN 'SKA'
WHEN 8 THEN 'OTROS'
ELSE 'SIN GENERO' END
) AS DETALLE_GENERO,DURACION, CANTANTE,
IDIOMA,(
CASE IDIOMA
WHEN 1 THEN 'INGLES'
WHEN 2 THEN 'ESPAÑOL'
WHEN 3 THEN 'FRANCES'
WHEN 4 THEN 'ALEMAN'
WHEN 5 THEN 'OTROS'
ELSE 'SIN DEFINIR' END) AS DETALLE_IDIOMA
FROM CANCION;

SELECT COUNT(ID) CONTADOR, GENERO ,(
CASE GENERO 
WHEN 1 THEN 'POP'
WHEN 2 THEN 'ROCK'
WHEN 3 THEN 'REGUETTON'
WHEN 4 THEN 'BALADA'
WHEN 5 THEN 'CUMBIA'
WHEN 6 THEN 'SALSA'
WHEN 7 THEN 'SKA'
WHEN 8 THEN 'OTROS'
ELSE 'SIN GENERO' END
) AS DETALLE_GENERO FROM CANCION GROUP BY GENERO;


