CREATE TABLE PRODUCTO(
ID_PRODUCTO NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(100) UNIQUE,
MARCA NVARCHAR2(100),
PRECIO NUMBER,
FECHA_ALTA DATE,
CONSTRAINT CHECK_PRODUCTO CHECK(MARCA IN('SABRITAS','BARCEL', 'SAMSUNG', 'KELLOGS', 'FUT'))
);

CREATE TABLE BIT_PRODUCTO(
 ID_BITACORA NUMBER PRIMARY KEY,
 ID_PRODUCTO NUMBER,
 NOMBRE NVARCHAR2(100),
 MARCA NVARCHAR2(100),
 PRECIO NUMBER,
 FECHA_ALTA DATE,
 USUARIO NVARCHAR2(100),
 FECHA_REGISTRO DATE,
 ACCION NVARCHAR2(100),
 NOMBRE_OLD NVARCHAR2(100),
 PRECIO_OLD NUMBER,
 FECHA_ALTA_OLD DATE,
 MARCA_OLD NVARCHAR2(100)
 );
 
 