CREATE TABLE PADRE(
ID_PADRE NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(100),
APP NVARCHAR2(100),
APM NVARCHAR2(100),
EDAD NUMBER,
FECHA_NACIMIENTO DATE,
PAIS NVARCHAR2(100)
);

INSERT INTO PADRE VALUES(1, 'GOUKU', 'GONZALES', 'GONZALES',35, '02/02/1990', 'PUEBLA');
INSERT INTO PAdRE VALUES(2, 'HOMERO', 'SIMPSON', 'GONZALES',31, '04/05/1992', 'SPRINGFIELD');
INSERT INTO PADRE VALUES(3, 'RICK', 'SANCHEZ', 'GONZALES',60, '02/04/1990', 'USA');

CREATE TABLE HIJO (
ID NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(100),
APP NVARCHAR2(100),
EDAD NUMBER,
ID_PADRE NUMBER,
CONSTRAINT FK_HIJO_PADRE FOREIGN KEY(ID_PADRE) REFERENCES PADRE(ID_PADRE)
);


INSERT INTO HIJO  VALUES(1, 'GOHAN', 'GONZALES', 25, 1);
INSERT INTO HIJO  VALUES(2, 'GOTEN', 'GONZALES', 15, 1);

INSERT INTO HIJO VALUES (3,'LISA', 'SIMPSON', 10, 2);

INSERT INTO HIJO VALUES(4, 'BETH', 'SANCHEZ', 25, 3);

SELECT * FROM HIJO;

SELECT HIJO.ID ID_H, HIJO.NOMBRE NOM_H, HIJO.APP APP_H, HIJO.EDAD EDAD_HIJO,
PADRE.ID_PADRE ID_P, PADRE.NOMBRE NOM_P, PADRE.APP APP_P 
FROM HIJO
INNER JOIN PADRE
ON padre.id_padre = hijo.id_padre;



CREATE TABLE SISTEMAOP(
ID_SO NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(100)
);

CREATE TABLE MARCA(
ID_MARCA NUMBER,
NOMBRE NVARCHAR2(100),
PAIS NVARCHAR2(100),
SLOGAN NVARCHAR2(100)
);

CREATE TABLE CELULAR2(
ID NUMBER PRIMARY KEY,
MODELO NVARCHAR2(100),
PRECIO NUMBER,
RAM NUMBER,
ID_MARCA NUMBER,
ID_SO NUMBER,
CONSTRAINT FK_MARCA_CEL FOREIGN KEY(ID_MARCA) REFERENCES MARCA(ID_MARCA),
CONSTRAINT FK_SO_CEL FOREIGN KEY(ID_SO) REFERENCES SISTEMAOP(ID_SO)
);