INSERT INTO CANCION VALUES (1,'HAPPY', 1, 120, 'MITSKI', 1);
INSERT INTO CANCION VALUES (2,'TRISTE CACNION DE AMOR', 2, 90, 'ELTRI', 2);
INSERT INTO CANCION VALUES (3,'ARREGLAME EL ALMA', 7, 130, 'PANTEONROCOCO', 2);
INSERT INTO CANCION VALUES (4,'MUJER CONTRA MUJER', 1, 600, 'MECANO', 2);
INSERT INTO CANCION VALUES (5, 'QUIERO VER', 2, 120, 'CAFETACUVA', 2);
INSERT INTO CANCION VALUES (6, 'DUTCHLAND', 2, 150, 'RAMMSTEIN', 4);
INSERT INTO CANCION VALUES (7, 'PEDRO NAVAJA', 5, 80, 'RUBEN BLADES', 2);
INSERT INTO CANCION VALUES (8, 'CHUNTARO STYLE', 8, 130, 'LA MALDITA VECINDAD', 2);
INSERT INTO CANCION VALUES (9, 'KANDY PERREO', 3, 190, 'NOSE', 2);
INSERT INTO CANCION VALUES (10 ,'MON AMOUR MON AMIE', 1, 97, 'LAFORETTE', 3);
SELECT * FROM CANCION;

SELECT ID, NOMBRE,
GENERO,(
CASE GENERO 
WHEN 1 THEN 'POP'
WHEN 2 THEN 'ROCK'
WHEN 3 THEN 'REGUETTON'
WHEN 4 THEN 'BALADA'
WHEN 5 THEN 'CUMBIA'
WHEN 6 THEN 'SALSA'
WHEN 7 THEN 'SKA'
WHEN 8 THEN 'OTROS'
ELSE 'SIN GENERO' END
) AS DETALLE_GENERO,DURACION, CANTANTE,
IDIOMA,(
CASE IDIOMA
WHEN 1 THEN 'INGLES'
WHEN 2 THEN 'ESPAÑOL'
WHEN 3 THEN 'FRANCES'
WHEN 4 THEN 'ALEMAN'
WHEN 5 THEN 'OTROS'
ELSE 'SIN DEFINIR' END) AS DETALLE_IDIOMA
FROM CANCION;

SELECT COUNT(ID) AS CONTADOR, 
GENERO ,(
CASE GENERO 
WHEN 1 THEN 'POP'
WHEN 2 THEN 'ROCK'
WHEN 3 THEN 'REGUETTON'
WHEN 4 THEN 'BALADA'
WHEN 5 THEN 'CUMBIA'
WHEN 6 THEN 'SALSA'
WHEN 7 THEN 'SKA'
WHEN 8 THEN 'OTROS'
ELSE 'SIN GENERO' END
) AS DETALLE_GENERO FROM CANCION GROUP BY GENERO;


SELECT ID, NOMBRE,
GENERO,(
CASE GENERO 
WHEN 1 THEN 'POP'
WHEN 2 THEN 'ROCK'
WHEN 3 THEN 'REGUETTON'
WHEN 4 THEN 'BALADA'
WHEN 5 THEN 'CUMBIA'
WHEN 6 THEN 'SALSA'
WHEN 7 THEN 'SKA'
WHEN 8 THEN 'OTROS'
ELSE 'SIN GENERO' END
) AS DETALLE_GENERO,DURACION, CANTANTE,
IDIOMA,(
CASE IDIOMA
WHEN 1 THEN 'INGLES'
WHEN 2 THEN 'ESPAÑOL'
WHEN 3 THEN 'FRANCES'
WHEN 4 THEN 'ALEMAN'
WHEN 5 THEN 'OTROS'
ELSE 'SIN DEFINIR' END) AS DETALLE_IDIOMA
FROM CANCION WHERE DURACION = (SELECT MAX(DURACION) DURACION_MAXIMA FROM CANCION);

SELECT ID, NOMBRE,
GENERO,(
CASE GENERO 
WHEN 1 THEN 'POP'
WHEN 2 THEN 'ROCK'
WHEN 3 THEN 'REGUETTON'
WHEN 4 THEN 'BALADA'
WHEN 5 THEN 'CUMBIA'
WHEN 6 THEN 'SALSA'
WHEN 7 THEN 'SKA'
WHEN 8 THEN 'OTROS'
ELSE 'SIN GENERO' END
) AS DETALLE_GENERO,DURACION, CANTANTE,
IDIOMA,(
CASE IDIOMA
WHEN 1 THEN 'INGLES'
WHEN 2 THEN 'ESPAÑOL'
WHEN 3 THEN 'FRANCES'
WHEN 4 THEN 'ALEMAN'
WHEN 5 THEN 'OTROS'
ELSE 'SIN DEFINIR' END) AS DETALLE_IDIOMA
FROM CANCION WHERE DURACION = (SELECT MIN(DURACION) DURACION_MAXIMA FROM CANCION);

commit;

CREATE TABLE FUTBOL(
ID NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(100),
LIGA NUMBER,
PAIS NUMBER,
ANIOS NUMBER,
MASCOTA NVARCHAR2(100),
TROFEOS NUMBER
);

INSERT INTO FUTBOL VALUES(1, 'CHIVAS', 1,1, 70, 'CHIVO', 9);

INSERT INTO FUTBOL VALUES(2, 'JUVENTUS', 2,2, 50, 'VACA', 8);
INSERT INTO FUTBOL VALUES(3, 'MADRID', 5,5, 80, 'BUHI', 15);
INSERT INTO FUTBOL VALUES(4, 'INTER DE MILAN', 3,3, 98, 'AGUILA', 9);
INSERT INTO FUTBOL VALUES(5, 'BAYERN', 4,4, 55, 'TANQUE', 56);
INSERT INTO FUTBOL VALUES(6, 'FRANKFURT', 4,4, 67, 'SALCHICHA', 2);
INSERT INTO FUTBOL VALUES(7, 'LAZZIO', 2,3, 34, 'SDS', 7);
INSERT INTO FUTBOL VALUES(8, 'CHELSEA', 1,1, 70, 'GATO', 5);
INSERT INTO FUTBOL VALUES(9, 'LIVERPOOL', 3, 3,67, 'TIGRE', 67);


SELECT * FROM FUTBOL;

SELECT ID, NOMBRE,
LIGA,(
CASE LIGA
WHEN 1 THEN 'MX'
WHEN 2 THEN 'SERIE A'
WHEN 3 THEN 'PREMIER'
WHEN 4 THEN 'BUNDESLIGA'
WHEN 5 THEN 'OTROS'
ELSE 'SIN LIGA' END
) AS DETALLE_GENERO,
PAIS,(
CASE PAIS
WHEN 1 THEN 'MEXICO'
WHEN 2 THEN 'ITALIA'
WHEN 3 THEN 'INGLATERRA'
WHEN 4 THEN 'ALEMANIA'
WHEN 5 THEN 'OTROS'
ELSE 'SIN DEFINIR' END
) AS DETALLE_IDIOMA,
ANIOS, MASCOTA, TROFEOS
FROM FUTBOL;

SELECT COUNT(ID) AS CONTADOR, 
LIGA,(
CASE LIGA
WHEN 1 THEN 'MX'
WHEN 2 THEN 'SERIE A'
WHEN 3 THEN 'PREMIER'
WHEN 4 THEN 'BUNDESLIGA'
WHEN 5 THEN 'OTROS'
ELSE 'SIN LIGA' END
) AS DETALLE_GENERO FROM FUTBOL GROUP BY LIGA;


